import type { Express } from 'express';

import jobs_get_190 from "./api/jobs/GET";
import jobs_post_191 from "./api/jobs/POST";
import jobs_id_get_192 from "./api/jobs/[id]/GET";
import jobs_id_put_193 from "./api/jobs/[id]/PUT";
import jobs_id_costs_get_194 from "./api/jobs/[id]/costs/GET";
import jobs_id_costs_post_195 from "./api/jobs/[id]/costs/POST";
import jobs_id_costs_export_get_196 from "./api/jobs/[id]/costs/export/GET";
import jobs_id_costs_costId_delete_197 from "./api/jobs/[id]/costs/[costId]/DELETE";
import jobs_id_costs_costId_put_198 from "./api/jobs/[id]/costs/[costId]/PUT";
import jobs_id_costs_costId_receipt_get_199 from "./api/jobs/[id]/costs/[costId]/receipt/GET";
import jobs_id_costs_costId_receipt_post_200 from "./api/jobs/[id]/costs/[costId]/receipt/POST";
import jobs_id_delays_get_201 from "./api/jobs/[id]/delays/GET";
import jobs_id_delays_post_202 from "./api/jobs/[id]/delays/POST";
import jobs_id_delays_delayId_delete_203 from "./api/jobs/[id]/delays/[delayId]/DELETE";
import jobs_id_delays_delayId_put_204 from "./api/jobs/[id]/delays/[delayId]/PUT";
import jobs_id_files_get_205 from "./api/jobs/[id]/files/GET";
import jobs_id_forms_get_206 from "./api/jobs/[id]/forms/GET";
import jobs_id_forms_post_207 from "./api/jobs/[id]/forms/POST";
import jobs_id_ledger_get_208 from "./api/jobs/[id]/ledger/GET";
import jobs_id_ledger_post_209 from "./api/jobs/[id]/ledger/POST";
import jobs_id_ledger_export_get_210 from "./api/jobs/[id]/ledger/export/GET";
import jobs_id_ledger_sync_post_211 from "./api/jobs/[id]/ledger/sync/POST";
import jobs_id_ledger_entryId_delete_212 from "./api/jobs/[id]/ledger/[entryId]/DELETE";
import jobs_id_ledger_entryId_put_213 from "./api/jobs/[id]/ledger/[entryId]/PUT";
import jobs_id_ledger_entryId_correct_post_214 from "./api/jobs/[id]/ledger/[entryId]/correct/POST";
import jobs_id_photos_get_215 from "./api/jobs/[id]/photos/GET";
import jobs_id_photos_post_216 from "./api/jobs/[id]/photos/POST";
import jobs_id_photos_photoId_delete_217 from "./api/jobs/[id]/photos/[photoId]/DELETE";
import jobs_id_photos_photoId_patch_218 from "./api/jobs/[id]/photos/[photoId]/PATCH";
import jobs_id_photos_photoId_download_get_219 from "./api/jobs/[id]/photos/[photoId]/download/GET";
import jobs_id_photos_photoId_replace_post_220 from "./api/jobs/[id]/photos/[photoId]/replace/POST";
import jobs_id_progress_get_221 from "./api/jobs/[id]/progress/GET";
import jobs_id_progress_put_222 from "./api/jobs/[id]/progress/PUT";
import jobs_id_progress_sync_post_223 from "./api/jobs/[id]/progress/sync/POST";
import jobs_id_purchase_orders_get_224 from "./api/jobs/[id]/purchase-orders/GET";
import jobs_id_purchase_orders_post_225 from "./api/jobs/[id]/purchase-orders/POST";
import jobs_id_purchase_orders_poId_delete_226 from "./api/jobs/[id]/purchase-orders/[poId]/DELETE";
import jobs_id_purchase_orders_poId_get_227 from "./api/jobs/[id]/purchase-orders/[poId]/GET";
import jobs_id_purchase_orders_poId_put_228 from "./api/jobs/[id]/purchase-orders/[poId]/PUT";
import jobs_id_purchase_orders_poId_pdf_get_229 from "./api/jobs/[id]/purchase-orders/[poId]/pdf/GET";
import jobs_id_swms_get_230 from "./api/jobs/[id]/swms/GET";
import jobs_id_swms_post_231 from "./api/jobs/[id]/swms/POST";
import jobs_id_swms_swmsId_signoff_post_232 from "./api/jobs/[id]/swms/[swmsId]/signoff/POST";
import jobs_id_todos_get_233 from "./api/jobs/[id]/todos/GET";
import jobs_id_todos_post_234 from "./api/jobs/[id]/todos/POST";
import jobs_id_todos_todoId_delete_235 from "./api/jobs/[id]/todos/[todoId]/DELETE";
import jobs_id_todos_todoId_put_236 from "./api/jobs/[id]/todos/[todoId]/PUT";

export function register(app: Express): void {
  app.get("/api/jobs", jobs_get_190);
  app.post("/api/jobs", jobs_post_191);
  app.get("/api/jobs/:id", jobs_id_get_192);
  app.put("/api/jobs/:id", jobs_id_put_193);
  app.get("/api/jobs/:id/costs", jobs_id_costs_get_194);
  app.post("/api/jobs/:id/costs", jobs_id_costs_post_195);
  app.get("/api/jobs/:id/costs/export", jobs_id_costs_export_get_196);
  app.delete("/api/jobs/:id/costs/:costId", jobs_id_costs_costId_delete_197);
  app.put("/api/jobs/:id/costs/:costId", jobs_id_costs_costId_put_198);
  app.get("/api/jobs/:id/costs/:costId/receipt", jobs_id_costs_costId_receipt_get_199);
  app.post("/api/jobs/:id/costs/:costId/receipt", jobs_id_costs_costId_receipt_post_200);
  app.get("/api/jobs/:id/delays", jobs_id_delays_get_201);
  app.post("/api/jobs/:id/delays", jobs_id_delays_post_202);
  app.delete("/api/jobs/:id/delays/:delayId", jobs_id_delays_delayId_delete_203);
  app.put("/api/jobs/:id/delays/:delayId", jobs_id_delays_delayId_put_204);
  app.get("/api/jobs/:id/files", jobs_id_files_get_205);
  app.get("/api/jobs/:id/forms", jobs_id_forms_get_206);
  app.post("/api/jobs/:id/forms", jobs_id_forms_post_207);
  app.get("/api/jobs/:id/ledger", jobs_id_ledger_get_208);
  app.post("/api/jobs/:id/ledger", jobs_id_ledger_post_209);
  app.get("/api/jobs/:id/ledger/export", jobs_id_ledger_export_get_210);
  app.post("/api/jobs/:id/ledger/sync", jobs_id_ledger_sync_post_211);
  app.delete("/api/jobs/:id/ledger/:entryId", jobs_id_ledger_entryId_delete_212);
  app.put("/api/jobs/:id/ledger/:entryId", jobs_id_ledger_entryId_put_213);
  app.post("/api/jobs/:id/ledger/:entryId/correct", jobs_id_ledger_entryId_correct_post_214);
  app.get("/api/jobs/:id/photos", jobs_id_photos_get_215);
  app.post("/api/jobs/:id/photos", jobs_id_photos_post_216);
  app.delete("/api/jobs/:id/photos/:photoId", jobs_id_photos_photoId_delete_217);
  app.patch("/api/jobs/:id/photos/:photoId", jobs_id_photos_photoId_patch_218);
  app.get("/api/jobs/:id/photos/:photoId/download", jobs_id_photos_photoId_download_get_219);
  app.post("/api/jobs/:id/photos/:photoId/replace", jobs_id_photos_photoId_replace_post_220);
  app.get("/api/jobs/:id/progress", jobs_id_progress_get_221);
  app.put("/api/jobs/:id/progress", jobs_id_progress_put_222);
  app.post("/api/jobs/:id/progress/sync", jobs_id_progress_sync_post_223);
  app.get("/api/jobs/:id/purchase-orders", jobs_id_purchase_orders_get_224);
  app.post("/api/jobs/:id/purchase-orders", jobs_id_purchase_orders_post_225);
  app.delete("/api/jobs/:id/purchase-orders/:poId", jobs_id_purchase_orders_poId_delete_226);
  app.get("/api/jobs/:id/purchase-orders/:poId", jobs_id_purchase_orders_poId_get_227);
  app.put("/api/jobs/:id/purchase-orders/:poId", jobs_id_purchase_orders_poId_put_228);
  app.get("/api/jobs/:id/purchase-orders/:poId/pdf", jobs_id_purchase_orders_poId_pdf_get_229);
  app.get("/api/jobs/:id/swms", jobs_id_swms_get_230);
  app.post("/api/jobs/:id/swms", jobs_id_swms_post_231);
  app.post("/api/jobs/:id/swms/:swmsId/signoff", jobs_id_swms_swmsId_signoff_post_232);
  app.get("/api/jobs/:id/todos", jobs_id_todos_get_233);
  app.post("/api/jobs/:id/todos", jobs_id_todos_post_234);
  app.delete("/api/jobs/:id/todos/:todoId", jobs_id_todos_todoId_delete_235);
  app.put("/api/jobs/:id/todos/:todoId", jobs_id_todos_todoId_put_236);
}
