import type { Express } from 'express';

export function register(
  app: Express,
  safety_ai_draft_post_562: any,
  safety_documents_get_563: any,
  safety_documents_post_564: any,
  safety_documents_id_delete_565: any,
  safety_documents_id_download_get_566: any,
  safety_generated_posters_get_567: any,
  safety_generated_posters_post_568: any,
  safety_generated_posters_id_delete_569: any,
  safety_job_safety_plans_get_570: any,
  safety_job_safety_plans_post_571: any,
  safety_job_safety_plans_id_delete_572: any,
  safety_job_safety_plans_id_put_573: any,
  safety_job_swms_get_574: any,
  safety_job_swms_post_575: any,
  safety_job_swms_id_delete_576: any,
  safety_job_swms_id_get_577: any,
  safety_job_swms_id_put_578: any,
  safety_job_swms_id_share_token_post_579: any,
  safety_job_swms_id_signoffs_get_580: any,
  safety_job_swms_id_signoffs_post_581: any,
  safety_job_swms_id_signoffs_signoffId_delete_582: any,
  safety_plans_get_583: any,
  safety_plans_post_584: any,
  safety_plans_seed_post_585: any,
  safety_plans_id_delete_586: any,
  safety_plans_id_put_587: any,
  safety_plans_id_export_get_588: any,
  safety_plans_id_pack_get_589: any,
  safety_posters_get_590: any,
  safety_posters_post_591: any,
  safety_posters_id_delete_592: any,
  safety_swms_get_593: any,
  safety_swms_post_594: any,
  safety_swms_seed_post_596: any,
  safety_swms_id_delete_597: any,
  safety_swms_id_get_598: any,
  safety_swms_id_put_599: any,
  safety_swms_id_duplicate_post_600: any,
  safety_swms_id_export_get_601: any,
): void {
  app.post("/api/safety/ai/draft", safety_ai_draft_post_562);
  app.get("/api/safety/documents", safety_documents_get_563);
  app.post("/api/safety/documents", safety_documents_post_564);
  app.delete("/api/safety/documents/:id", safety_documents_id_delete_565);
  app.get("/api/safety/documents/:id/download", safety_documents_id_download_get_566);
  app.get("/api/safety/generated-posters", safety_generated_posters_get_567);
  app.post("/api/safety/generated-posters", safety_generated_posters_post_568);
  app.delete("/api/safety/generated-posters/:id", safety_generated_posters_id_delete_569);
  app.get("/api/safety/job-safety-plans", safety_job_safety_plans_get_570);
  app.post("/api/safety/job-safety-plans", safety_job_safety_plans_post_571);
  app.delete("/api/safety/job-safety-plans/:id", safety_job_safety_plans_id_delete_572);
  app.put("/api/safety/job-safety-plans/:id", safety_job_safety_plans_id_put_573);
  app.get("/api/safety/job-swms", safety_job_swms_get_574);
  app.post("/api/safety/job-swms", safety_job_swms_post_575);
  app.delete("/api/safety/job-swms/:id", safety_job_swms_id_delete_576);
  app.get("/api/safety/job-swms/:id", safety_job_swms_id_get_577);
  app.put("/api/safety/job-swms/:id", safety_job_swms_id_put_578);
  app.post("/api/safety/job-swms/:id/share-token", safety_job_swms_id_share_token_post_579);
  app.get("/api/safety/job-swms/:id/signoffs", safety_job_swms_id_signoffs_get_580);
  app.post("/api/safety/job-swms/:id/signoffs", safety_job_swms_id_signoffs_post_581);
  app.delete("/api/safety/job-swms/:id/signoffs/:signoffId", safety_job_swms_id_signoffs_signoffId_delete_582);
  app.get("/api/safety/plans", safety_plans_get_583);
  app.post("/api/safety/plans", safety_plans_post_584);
  app.post("/api/safety/plans/seed", safety_plans_seed_post_585);
  app.delete("/api/safety/plans/:id", safety_plans_id_delete_586);
  app.put("/api/safety/plans/:id", safety_plans_id_put_587);
  app.get("/api/safety/plans/:id/export", safety_plans_id_export_get_588);
  app.get("/api/safety/plans/:id/pack", safety_plans_id_pack_get_589);
  app.get("/api/safety/posters", safety_posters_get_590);
  app.post("/api/safety/posters", safety_posters_post_591);
  app.delete("/api/safety/posters/:id", safety_posters_id_delete_592);
  app.get("/api/safety/swms", safety_swms_get_593);
  app.post("/api/safety/swms", safety_swms_post_594);
  app.post("/api/safety/swms/seed", safety_swms_seed_post_596);
  app.delete("/api/safety/swms/:id", safety_swms_id_delete_597);
  app.get("/api/safety/swms/:id", safety_swms_id_get_598);
  app.put("/api/safety/swms/:id", safety_swms_id_put_599);
  app.post("/api/safety/swms/:id/duplicate", safety_swms_id_duplicate_post_600);
  app.get("/api/safety/swms/:id/export", safety_swms_id_export_get_601);
}
