/**
 * /share/asset-report/:token — Public read-only inspection report page
 * No login required. Token-validated.
 */
import { useState, useEffect } from 'react';
import { useParams } from "react-router";
import { Helmet } from '@dr.pogodin/react-helmet';
import { asset_report_share } from 'virtual:content';
import { Building2, ClipboardCheck, AlertTriangle, FileText, Calendar, MapPin, Loader2, Lock, CheckCircle2, XCircle } from 'lucide-react';
interface ReportData {
  inspection: {
    id: number;
    report_no: string | null;
    report_title: string | null;
    inspection_date: string | null;
    overall_status: string;
    notes: string | null;
    asset_name: string;
    asset_acronym: string | null;
    asset_address: string | null;
    asset_type: string;
  };
  defects: Array<{
    id: number;
    title: string;
    severity: string;
    location: string | null;
    description: string | null;
    status: string;
    due_date: string | null;
  }>;
  media: Array<{
    id: number;
    file_path: string;
    file_name: string;
    mime_type: string | null;
    category: string;
  }>;
  tenders: Array<{
    id: number;
    code: string | null;
    contractor_name: string | null;
    award_status: string;
    quote_amount: number | null;
  }>;
  scope: string;
  expiresAt: string | null;
}
const SEVERITY_COLORS: Record<string, string> = {
  low: 'bg-slate-100 text-slate-600 border-slate-200',
  med: 'bg-yellow-50 text-yellow-700 border-yellow-200',
  high: 'bg-violet-50 text-violet-800 border-violet-200',
  critical: 'bg-red-50 text-red-700 border-red-200'
};
const STATUS_COLORS: Record<string, string> = {
  open: 'text-red-600',
  in_progress: 'text-blue-600',
  resolved: 'text-emerald-600'
};
export default function AssetReportSharePage() {
  const {
    token
  } = useParams<{
    token: string;
  }>();
  const [data, setData] = useState<ReportData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => {
    if (!token) return;
    fetch(`/api/asset-manager/reports/${token}`).then(r => {
      if (!r.ok) throw new Error('Link not found or expired');
      return r.json() as Promise<ReportData>;
    }).then(setData).catch((e: Error) => setError(e.message)).finally(() => setLoading(false));
  }, [token]);
  if (loading) {
    return <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <Loader2 size={24} className="animate-spin text-slate-400" />
      </div>;
  }
  if (error || !data) {
    return <div className="min-h-screen bg-slate-50 flex items-center justify-center p-6">
        <div className="max-w-sm w-full bg-white rounded-2xl border border-slate-200 shadow-sm p-8 text-center">
          <Lock size={32} className="text-slate-400 mx-auto mb-3" />
          <h1 className="text-lg font-bold text-slate-800 mb-2">{asset_report_share.linkUnavailable}</h1>
          <p className="text-sm text-slate-500">{error || asset_report_share.linkExpiredMessage}</p>
        </div>
      </div>;
  }
  const {
    inspection,
    defects,
    media,
    tenders
  } = data;
  const openDefects = defects.filter(d => d.status !== 'resolved');
  const photos = media.filter(m => m.mime_type?.startsWith('image/'));
  return <div className="min-h-screen bg-slate-50">
      <Helmet>
        <title>{inspection.report_title || `Inspection Report #${inspection.id}`} — IWIllBUIlD</title>
        <meta name="description" content={`View-only inspection report for ${inspection.asset_name}. Generated by IWIllBUIlD.`} />
        <link rel="canonical" href={`https://iwillbuild.com/share/asset-report/${token}`} />
        <meta name="robots" content="noindex" />
      </Helmet>

      {/* Header */}
      <div className="bg-white border-b border-slate-200 px-6 py-5">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Inspection Report</span>
            {data.expiresAt && <span className="text-xs text-slate-400 ml-auto">
                Expires {new Date(data.expiresAt).toLocaleDateString('en-AU', {
              day: 'numeric',
              month: 'short',
              year: 'numeric'
            })}
              </span>}
          </div>
          <h1 className="text-2xl font-bold text-slate-900">{inspection.report_title || `Inspection #${inspection.id}`}</h1>
          {inspection.report_no && <p className="text-sm text-slate-500 mt-0.5">Report No. {inspection.report_no}</p>}
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-6 py-8 flex flex-col gap-8">
        {/* Asset info */}
        <div className="bg-white rounded-2xl border border-slate-200 p-6">
          <h2 className="text-sm font-bold text-slate-700 mb-4 flex items-center gap-2">
            <Building2 size={15} className="text-slate-500" />
            <span>{asset_report_share.assetDetails}</span>
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <p className="text-xs text-slate-500 mb-0.5">Asset Name</p>
              <p className="text-sm font-semibold text-slate-800">{inspection.asset_name}{inspection.asset_acronym ? ` (${inspection.asset_acronym})` : ''}</p>
            </div>
            <div>
              <p className="text-xs text-slate-500 mb-0.5">Asset Type</p>
              <p className="text-sm font-semibold text-slate-800 capitalize">{inspection.asset_type}</p>
            </div>
            {inspection.asset_address && <div className="sm:col-span-2">
                <p className="text-xs text-slate-500 mb-0.5 flex items-center gap-1"><MapPin size={10} />Location</p>
                <p className="text-sm text-slate-700">{inspection.asset_address}</p>
              </div>}
          </div>
        </div>

        {/* Inspection summary */}
        <div className="bg-white rounded-2xl border border-slate-200 p-6">
          <h2 className="text-sm font-bold text-slate-700 mb-4 flex items-center gap-2">
            <ClipboardCheck size={15} className="text-slate-500" />
            <span>{asset_report_share.inspectionSummary}</span>
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div>
              <p className="text-xs text-slate-500 mb-0.5 flex items-center gap-1"><Calendar size={10} />Date</p>
              <p className="text-sm font-semibold text-slate-800">
                {inspection.inspection_date ? new Date(inspection.inspection_date).toLocaleDateString('en-AU', {
                day: 'numeric',
                month: 'long',
                year: 'numeric'
              }) : '—'}
              </p>
            </div>
            <div>
              <p className="text-xs text-slate-500 mb-0.5">Status</p>
              <p className="text-sm font-semibold text-slate-800 capitalize">{inspection.overall_status.replace('_', ' ')}</p>
            </div>
            <div>
              <p className="text-xs text-slate-500 mb-0.5">Open Defects</p>
              <p className={`text-sm font-bold ${openDefects.length > 0 ? 'text-red-600' : 'text-emerald-600'}`}>{openDefects.length}</p>
            </div>
          </div>
          {inspection.notes && <div className="mt-4 pt-4 border-t border-slate-100">
              <p className="text-xs text-slate-500 mb-1">Notes</p>
              <p className="text-sm text-slate-700 whitespace-pre-wrap">{inspection.notes}</p>
            </div>}
        </div>

        {/* Defects */}
        {defects.length > 0 && <div className="bg-white rounded-2xl border border-slate-200 p-6">
            <h2 className="text-sm font-bold text-slate-700 mb-4 flex items-center gap-2">
              <AlertTriangle size={15} className="text-slate-500" />
              <span>{asset_report_share.defectsLabel} ({defects.length})</span>
            </h2>
            <div className="flex flex-col gap-3">
              {defects.map(d => <div key={d.id} className="flex items-start gap-3 p-3 bg-slate-50 rounded-xl border border-slate-100">
                  <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-semibold border flex-shrink-0 mt-0.5 ${SEVERITY_COLORS[d.severity] ?? 'bg-slate-100 text-slate-600 border-slate-200'}`}>
                    {d.severity}
                  </span>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <p className="text-sm font-semibold text-slate-800">{d.title}</p>
                      <span className={`text-xs font-semibold ${STATUS_COLORS[d.status] ?? 'text-slate-500'}`}>
                        {d.status === 'resolved' ? <CheckCircle2 size={12} className="inline" /> : <XCircle size={12} className="inline" />}
                        {' '}{d.status.replace('_', ' ')}
                      </span>
                    </div>
                    {d.location && <p className="text-xs text-slate-500 mt-0.5">@ {d.location}</p>}
                    {d.description && <p className="text-xs text-slate-600 mt-1">{d.description}</p>}
                    {d.due_date && <p className="text-xs text-slate-500 mt-1">Due: {new Date(d.due_date).toLocaleDateString('en-AU', {
                  day: 'numeric',
                  month: 'short',
                  year: 'numeric'
                })}</p>}
                  </div>
                </div>)}
            </div>
          </div>}

        {/* Tenders */}
        {tenders.length > 0 && <div className="bg-white rounded-2xl border border-slate-200 p-6">
            <h2 className="text-sm font-bold text-slate-700 mb-4 flex items-center gap-2">
              <FileText size={15} className="text-slate-500" />
              <span>{asset_report_share.tendersLabel} ({tenders.length})</span>
            </h2>
            <div className="flex flex-col gap-2">
              {tenders.map(t => <div key={t.id} className="flex items-center gap-3 p-3 bg-slate-50 rounded-xl border border-slate-100">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      {t.code && <span className="text-xs font-mono text-slate-500">{t.code}</span>}
                      <span className="text-sm font-semibold text-slate-800">{t.contractor_name || 'No contractor'}</span>
                    </div>
                    {t.quote_amount && <p className="text-xs text-slate-500 mt-0.5">${Number(t.quote_amount).toLocaleString('en-AU', {
                  minimumFractionDigits: 2
                })}</p>}
                  </div>
                  <span className="text-xs font-semibold text-slate-500 capitalize">{t.award_status}</span>
                </div>)}
            </div>
          </div>}

        {/* Photos */}
        {photos.length > 0 && <div className="bg-white rounded-2xl border border-slate-200 p-6">
            <h2 className="text-sm font-bold text-slate-700 mb-4"><span>{asset_report_share.photosLabel} ({photos.length})</span></h2>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-3">
              {photos.map(p => <a key={p.id} href={p.file_path} target="_blank" rel="noopener noreferrer" className="aspect-square rounded-xl overflow-hidden bg-slate-100 border border-slate-200 hover:opacity-90 transition-opacity">
                  <img src={p.file_path} alt={p.file_name} className="w-full h-full object-cover" loading="lazy" />
                </a>)}
            </div>
          </div>}

        {/* Footer */}
        <div className="text-center text-xs text-slate-400 pb-4">
          <span>{asset_report_share.footer}</span> &middot; <span>{asset_report_share.viewOnly}</span> &middot; {data.expiresAt ? `Expires ${new Date(data.expiresAt).toLocaleDateString('en-AU')}` : asset_report_share.noExpiry}
        </div>
      </div>
    </div>;
}
