/**
 * src/content/virtual-content-fallback.ts
 *
 * Runtime fallback for the `virtual:content` module used in Vitest and any
 * environment where the Vite build-time virtual module is not available.
 *
 * The real `virtual:content` is generated by the content_scaffold plugin at
 * build time. This file exports the same named exports with empty/minimal
 * values so that any module that imports from `virtual:content` doesn't crash
 * during tests or in environments without a full Vite build.
 *
 * Shape is derived from src/content/virtual-content.d.ts and
 * src/test/stubs/virtual-content.stub.ts.
 *
 * Keep in sync with the stub and the real virtual module shape.
 */

export const asset_manager: { TABS: string[] } = { TABS: [] };

export const asset_report_share: {
  linkUnavailable: string;
  linkExpiredMessage: string;
  assetDetails: string;
  inspectionSummary: string;
  defectsLabel: string;
  tendersLabel: string;
  photosLabel: string;
  noExpiry: string;
} = {
  linkUnavailable: '',
  linkExpiredMessage: '',
  assetDetails: '',
  inspectionSummary: '',
  defectsLabel: '',
  tendersLabel: '',
  photosLabel: '',
  noExpiry: '',
};

export const home: {
  tabs: string[];
  rows: Array<{ id: string; label: string; status: string; color: string }>;
} = { tabs: [], rows: [] };

export const roadmap: {
  phases: string[];
  GATES: Array<{
    id: string;
    label: string;
    status: string;
    criteria: string[];
    unblock: string;
  }>;
} = { phases: [], GATES: [] };

export const studio: { ALL_TYPES: string[]; CATEGORIES: string[] } = { ALL_TYPES: [], CATEGORIES: [] };

export const driver: {
  COST_CATEGORIES: Array<{ value: string; label: string; id: string }>;
} = { COST_CATEGORIES: [] };

export const job_site_prestart: {
  SITUATION_CHECKS: string[];
  EXECUTION_CHECKS: string[];
  ADMIN_CHECKS: string[];
} = {
  SITUATION_CHECKS: [
    'Weather / heat',
    'Site access',
    'Public interface',
    'Live electrical services',
    'Underground services',
    'Traffic / plant movement',
    'Other hazards',
  ],
  EXECUTION_CHECKS: [
    'Relevant SWMS reviewed',
    'Permits confirmed',
    'DBYD / services marked',
    'Plant pre-starts complete',
    'Exclusion zones set',
    'Traffic controls in place if required',
    'Spotter / observer assigned if required',
    'Critical controls explained',
  ],
  ADMIN_CHECKS: [
    'PPE worn / available',
    'First aid kit available',
    'Spill kit available',
    'Fire extinguisher available',
    'Water / shade available',
    'Waste controls in place',
    'Emergency access clear',
    'Amenities available if required',
  ],
};
