// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const asset_manager: { "TABS": Array<string> };
  export const asset_report_share: { "linkUnavailable": string; "linkExpiredMessage": string; "assetDetails": string; "inspectionSummary": string; "defectsLabel": string; "tendersLabel": string; "photosLabel": string; "noExpiry": string };
  export const driver: { "COST_CATEGORIES": Array<{ "value": string; "label": string; "id": string }> };
  export const forms: { "page": { "title": string; "heading": string; "metaDescription": string }; "FORM_TYPES": Array<string>; "emptyState": { "heading": string; "body": string }; "deleteConfirm": { "heading": string; "body": string; "confirmLabel": string; "deletingLabel": string; "cancelLabel": string }; "drawer": { "createHeading": string; "editHeading": string; "namePlaceholder": string; "categoryPlaceholder": string; "descriptionPlaceholder": string; "availabilityLabel": string; "activeLabel": string; "dashboardLabel": string; "jobsLabel": string; "fleetLabel": string } };
  export const home: { "tabs": Array<string>; "rows": Array<{ "id": string; "label": string; "status": string; "color": string }> };
  export const incident_detail: { "THIRD_PARTY_ROLES": Array<string> };
  export const incidents: { "INCIDENT_TYPES": Array<string> };
  export const job_field_docs: { "page": { "title": string; "heading": string; "metaDescription": string }; "emptyState": { "heading": string; "body": string; "addLabel": string }; "signOnRegister": { "heading": string; "workerNote": string; "noSignOnsBody": string }; "addDocModal": { "heading": string; "addLabel": string; "cancelLabel": string } };
  export const job_risky: { "HAZARD_OPTIONS": Array<string>; "PERMIT_TYPE_OPTIONS": Array<string> };
  export const job_site_prestart: { "SITUATION_CHECKS": Array<string>; "EXECUTION_CHECKS": Array<string>; "ADMIN_CHECKS": Array<string> };
  export const login: { "page": { "title": string; "metaDescription": string; "ogTitle": string; "ogDescription": string }; "heading": string; "subheading": string; "tabs": { "password": string; "pin": string }; "twoFactor": { "heading": string }; "banners": { "emailVerified": string }; "errors": { "missingCredentials": string; "pinLength": string; "pinVerifiedFallback": string }; "submitLabel": string };
  export const roadmap: { "phases": Array<string>; "GATES": Array<{ "id": string; "label": string; "status": string; "criteria": Array<string>; "unblock": string }> };
  export const studio: { "ALL_TYPES": Array<string>; "CATEGORIES": Array<string> };
}
