/**
 * src/content/virtual-content-fallback.ts
 *
 * Runtime fallback for the `virtual:content` module used in Vitest and any
 * environment where the Vite build-time virtual module is not available.
 *
 * The real `virtual:content` is generated by the content_scaffold plugin at
 * build time. This file exports the same named exports with empty/minimal
 * values so that any module that imports from `virtual:content` doesn't crash
 * during tests or in environments without a full Vite build.
 *
 * Shape is derived from src/content/virtual-content.d.ts and
 * src/test/stubs/virtual-content.stub.ts.
 *
 * Keep in sync with the stub and the real virtual module shape.
 */

export const asset_manager: { TABS: string[] } = { TABS: [] };

export const asset_report_share: {
  linkUnavailable: string;
  linkExpiredMessage: string;
  assetDetails: string;
  inspectionSummary: string;
  defectsLabel: string;
  tendersLabel: string;
  photosLabel: string;
  noExpiry: string;
} = {
  linkUnavailable: '',
  linkExpiredMessage: '',
  assetDetails: '',
  inspectionSummary: '',
  defectsLabel: '',
  tendersLabel: '',
  photosLabel: '',
  noExpiry: '',
};

export const home: {
  tabs: string[];
  rows: Array<{ id: string; label: string; status: string; color: string }>;
} = { tabs: [], rows: [] };

export const roadmap: {
  phases: string[];
  GATES: Array<{
    id: string;
    label: string;
    status: string;
    criteria: string[];
    unblock: string;
  }>;
} = { phases: [], GATES: [] };

export const studio: { ALL_TYPES: string[]; CATEGORIES: string[] } = { ALL_TYPES: [], CATEGORIES: [] };

export const driver: {
  COST_CATEGORIES: Array<{ value: string; label: string; id: string }>;
} = { COST_CATEGORIES: [] };

export const job_risky: {
  HAZARD_OPTIONS: string[];
  PERMIT_TYPE_OPTIONS: string[];
} = {
  HAZARD_OPTIONS: [
    'Working at heights', 'Electrical hazards', 'Confined space', 'Hot work / welding',
    'Hazardous chemicals', 'Heavy machinery', 'Excavation / trenching', 'Overhead work',
    'Slips, trips and falls', 'Manual handling', 'Noise exposure', 'UV / sun exposure',
    'Traffic management', 'Asbestos / hazardous materials', 'Other',
  ],
  PERMIT_TYPE_OPTIONS: [
    'Hot Work Permit', 'Confined Space Entry', 'Electrical Isolation', 'Working at Heights',
    'Excavation Permit', 'Crane / Lifting Operations', 'Hazardous Substances',
    'Environmental / Spill Risk', 'Other',
  ],
};

export const incidents: {
  INCIDENT_TYPES: string[];
} = {
  INCIDENT_TYPES: [
    'Injury', 'Near miss', 'Property damage', 'Environmental spill', 'Vehicle incident',
    'Plant/equipment incident', 'Public/client complaint', 'Unsafe condition', 'Other',
  ],
};

export const incident_detail: {
  THIRD_PARTY_ROLES: string[];
} = {
  THIRD_PARTY_ROLES: [
    'Client', 'Subcontractor', 'Supplier', 'Member of public', 'Authority/inspector', 'Other',
  ],
};

export const forms: {
  page: { title: string; heading: string; metaDescription: string };
  FORM_TYPES: string[];
  emptyState: { heading: string; body: string };
  deleteConfirm: { heading: string; body: string; confirmLabel: string; deletingLabel: string; cancelLabel: string };
  drawer: { createHeading: string; editHeading: string; namePlaceholder: string; categoryPlaceholder: string; descriptionPlaceholder: string; availabilityLabel: string; activeLabel: string; dashboardLabel: string; jobsLabel: string; fleetLabel: string };
} = {
  page: { title: 'Forms — IWILLBUILD', heading: 'Forms', metaDescription: 'Manage form templates for jobs, fleet, safety and company operations.' },
  FORM_TYPES: ['Job', 'Company', 'Fleet', 'Accounts'],
  emptyState: { heading: 'No form templates yet', body: 'Create your first form template to get started.' },
  deleteConfirm: { heading: 'Delete Template?', body: 'will be permanently deleted. This cannot be undone.', confirmLabel: 'Delete', deletingLabel: 'Deleting…', cancelLabel: 'Cancel' },
  drawer: { createHeading: 'New Form Template', editHeading: 'Edit Form Template', namePlaceholder: 'e.g. Site Induction Form', categoryPlaceholder: 'e.g. Safety, HR', descriptionPlaceholder: 'What is this form used for?', availabilityLabel: 'Availability', activeLabel: 'Active', dashboardLabel: 'Available on Dashboard', jobsLabel: 'Available for Jobs', fleetLabel: 'Available for Fleet' },
};

export const job_field_docs: {
  page: { title: string; heading: string; metaDescription: string };
  emptyState: { heading: string; body: string; addLabel: string };
  signOnRegister: { heading: string; workerNote: string; noSignOnsBody: string };
  addDocModal: { heading: string; addLabel: string; cancelLabel: string };
} = {
  page: { title: 'Field Docs | IWILLBUILD', heading: 'Field Docs', metaDescription: 'View, review and sign on to job documents in the field.' },
  emptyState: { heading: 'No documents added', body: 'Add SWMS documents to this job so workers can review and sign on.', addLabel: 'Add Document' },
  signOnRegister: { heading: 'Sign-on Register', workerNote: 'Workers can sign on from their phone — no login needed.', noSignOnsBody: 'Workers sign on via the share link on each document.' },
  addDocModal: { heading: 'Add Document to Job', addLabel: 'Add Docs', cancelLabel: 'Cancel' },
};

export const login: {
  page: { title: string; metaDescription: string; ogTitle: string; ogDescription: string };
  heading: string;
  subheading: string;
  tabs: { password: string; pin: string };
  twoFactor: { heading: string };
  banners: { emailVerified: string };
  errors: { missingCredentials: string; pinLength: string; pinVerifiedFallback: string };
  submitLabel: string;
} = {
  page: { title: 'Sign In — IWILLBUILD Portal', metaDescription: 'Sign in to the IWILLBUILD portal to manage jobs, crews, fleet, safety and more.', ogTitle: 'Sign In — IWILLBUILD Portal', ogDescription: 'Sign in to manage your construction jobs, fleet, safety docs and team.' },
  heading: 'Portal Sign In',
  subheading: 'Internal access only',
  tabs: { password: 'Password', pin: 'PIN Login' },
  twoFactor: { heading: 'Two-Factor Authentication' },
  banners: { emailVerified: 'Email verified — you\'re all set!' },
  errors: { missingCredentials: 'Please enter your email and PIN.', pinLength: 'PIN must be 4–6 digits.', pinVerifiedFallback: 'PIN verified. Please sign in with your password to complete login.' },
  submitLabel: 'Sign In',
};

export const job_site_prestart: {
  SITUATION_CHECKS: string[];
  EXECUTION_CHECKS: string[];
  ADMIN_CHECKS: string[];
} = {
  SITUATION_CHECKS: [
    'Weather / heat',
    'Site access',
    'Public interface',
    'Live electrical services',
    'Underground services',
    'Traffic / plant movement',
    'Other hazards',
  ],
  EXECUTION_CHECKS: [
    'Relevant SWMS reviewed',
    'Permits confirmed',
    'DBYD / services marked',
    'Plant pre-starts complete',
    'Exclusion zones set',
    'Traffic controls in place if required',
    'Spotter / observer assigned if required',
    'Critical controls explained',
  ],
  ADMIN_CHECKS: [
    'PPE worn / available',
    'First aid kit available',
    'Spill kit available',
    'Fire extinguisher available',
    'Water / shade available',
    'Waste controls in place',
    'Emergency access clear',
    'Amenities available if required',
  ],
};
