/**
 * purchase-order-pdf-document.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Canonical PO PDF builder — used by both the Finance and legacy job-scoped
 * PDF endpoints. Returns genuine PDF bytes (application/pdf, starts with %PDF).
 *
 * Uses pdf-lib (pure JS, Alpine/musl safe) via the existing lazy-import pattern.
 */

import { fetchPOForPdf } from './po-service.js';

// ── Types ─────────────────────────────────────────────────────────────────────

export interface POPdfResult {
  pdfBytes: Uint8Array;
  filename: string;
  poNumber: string;
  poStatus: string;
  companyName: string;
  contractorName: string;
  contractorEmail: string;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function fmtCurrency(n: number | string | null | undefined): string {
  const num = parseFloat(String(n ?? 0)) || 0;
  return num.toLocaleString('en-AU', { style: 'currency', currency: 'AUD', minimumFractionDigits: 2 });
}

function fmtDate(d: string | null | undefined): string {
  if (!d) return '—';
  try {
    return new Date(d).toLocaleDateString('en-AU', { day: 'numeric', month: 'short', year: 'numeric' });
  } catch { return String(d); }
}

function safeName(filename: string): string {
  return filename.replace(/[^a-z0-9_\-]/gi, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
}

// ── PDF builder ───────────────────────────────────────────────────────────────

export async function buildPOPdf(
  companyId: number,
  poId: number,
  jobId?: number | null,
): Promise<POPdfResult | null> {
  const data = await fetchPOForPdf(companyId, poId, jobId);
  if (!data) return null;

  const { po, lines, company, pdfSettings } = data;

  const pdfLib = await import('pdf-lib');
  const { PDFDocument, rgb, StandardFonts } = pdfLib;

  // ── Colours ──────────────────────────────────────────────────────────────────
  const PURPLE = rgb(0.486, 0.227, 0.929); // #7c3aed
  const WHITE  = rgb(1, 1, 1);
  const BLACK  = rgb(0, 0, 0);
  const SLATE  = rgb(0.243, 0.267, 0.322); // #3e4452
  const MUTED  = rgb(0.502, 0.533, 0.580);
  const LIGHT  = rgb(0.949, 0.953, 0.961); // #f2f3f5
  const RED    = rgb(0.863, 0.078, 0.235); // #dc1440
  const GREEN  = rgb(0.035, 0.545, 0.412); // #098b69
  const BLUE   = rgb(0.145, 0.388, 0.925); // #2563eb

  const statusColor: Record<string, ReturnType<typeof rgb>> = {
    draft: MUTED, sent: BLUE, completed: GREEN, paid: PURPLE, cancelled: RED,
  };

  const PAGE_W = 595.28;
  const PAGE_H = 841.89;
  const MARGIN = 44;
  const CONTENT_W = PAGE_W - MARGIN * 2;

  const doc = await PDFDocument.create();
  const boldFont    = await doc.embedFont(StandardFonts.HelveticaBold);
  const regularFont = await doc.embedFont(StandardFonts.Helvetica);

  const poStatus = String(po.status ?? 'draft');
  const isInternal  = po.assigned_to_type === 'internal';
  const isCancelled = poStatus === 'cancelled';
  const docTypeLabel = isInternal ? 'WORK ORDER' : 'PURCHASE ORDER';
  const poNumber = String(po.po_number ?? '');
  const companyName = String(company.company_name ?? 'IWILLBUILD');

  // ── Helper: add page ─────────────────────────────────────────────────────────
  function newPage() {
    const p = doc.addPage([PAGE_W, PAGE_H]);
    // Printer-friendly header: 3pt accent rule + plain dark text on white
    p.drawLine({ start: { x: 0, y: PAGE_H - 3 }, end: { x: PAGE_W, y: PAGE_H - 3 }, thickness: 3, color: PURPLE });
    p.drawText(companyName, { x: MARGIN, y: PAGE_H - 22, font: boldFont, size: 13, color: BLACK });
    p.drawText(docTypeLabel, { x: MARGIN, y: PAGE_H - 38, font: boldFont, size: 9, color: BLACK });
    const dateStr = new Date().toLocaleDateString('en-AU', { day: '2-digit', month: 'short', year: 'numeric' });
    const dw = regularFont.widthOfTextAtSize(dateStr, 8);
    p.drawText(dateStr, { x: PAGE_W - MARGIN - dw, y: PAGE_H - 22, font: regularFont, size: 8, color: MUTED });
    // Thin separator rule
    p.drawLine({ start: { x: MARGIN, y: PAGE_H - 48 }, end: { x: PAGE_W - MARGIN, y: PAGE_H - 48 }, thickness: 0.5, color: LIGHT });
    // Footer: thin rule + muted text (no filled band)
    p.drawLine({ start: { x: MARGIN, y: 22 }, end: { x: PAGE_W - MARGIN, y: 22 }, thickness: 0.5, color: LIGHT });
    const footerText = pdfSettings.footerText || pdfSettings.paymentTerms || '';
    if (footerText) {
      p.drawText(footerText.slice(0, 100), { x: MARGIN, y: 9, font: regularFont, size: 7, color: MUTED });
    } else {
      p.drawText('Generated by IWILLBUILD', { x: MARGIN, y: 9, font: regularFont, size: 7, color: MUTED });
    }
    return p;
  }

  // ── Helper: wrap text ────────────────────────────────────────────────────────
  function wrapText(text: string, font: typeof boldFont, size: number, maxW: number): string[] {
    const words = String(text ?? '').split(' ');
    const result: string[] = [];
    let cur = '';
    for (const w of words) {
      const test = cur ? `${cur} ${w}` : w;
      if (font.widthOfTextAtSize(test, size) <= maxW) { cur = test; }
      else { if (cur) result.push(cur); cur = w; }
    }
    if (cur) result.push(cur);
    return result.length ? result : [''];
  }

  // ── Page 1 ───────────────────────────────────────────────────────────────────
  let page = newPage();
  let y = PAGE_H - 64;
  let pageNum = 1;

  // PO number + status block — white bg, 3pt left accent rule, dark text
  page.drawLine({ start: { x: MARGIN, y: y - 32 }, end: { x: MARGIN, y: y + 6 }, thickness: 3, color: PURPLE });
  page.drawText(poNumber, { x: MARGIN + 10, y: y - 8, font: boldFont, size: 14, color: BLACK });
  page.drawText(String(po.title ?? ''), { x: MARGIN + 10, y: y - 22, font: regularFont, size: 9, color: MUTED });

  // Status — text only, no filled pill
  const sColor = statusColor[poStatus] ?? MUTED;
  const sLabel = poStatus.toUpperCase();
  const sLabelW = boldFont.widthOfTextAtSize(sLabel, 8);
  page.drawText(sLabel, { x: PAGE_W - MARGIN - sLabelW - 4, y: y - 18, font: boldFont, size: 8, color: sColor });
  y -= 50;

  // Cancelled banner
  if (isCancelled) {
    page.drawRectangle({ x: MARGIN, y: y - 28, width: CONTENT_W, height: 32, color: rgb(1, 0.95, 0.95) });
    page.drawLine({ start: { x: MARGIN, y: y - 28 }, end: { x: PAGE_W - MARGIN, y: y - 28 }, thickness: 1, color: RED });
    page.drawLine({ start: { x: MARGIN, y: y + 4 }, end: { x: PAGE_W - MARGIN, y: y + 4 }, thickness: 1, color: RED });
    page.drawText('CANCELLED', { x: MARGIN + 10, y: y - 10, font: boldFont, size: 11, color: RED });
    const note = String(po.cancelled_note ?? 'This Purchase Order has been cancelled.').slice(0, 80);
    page.drawText(note, { x: MARGIN + 100, y: y - 10, font: regularFont, size: 8, color: RED });
    y -= 44;
  }

  // Two-column info block: Job | Contractor
  const colW = (CONTENT_W - 12) / 2;
  const col2x = MARGIN + colW + 12;

  // Job box
  page.drawRectangle({ x: MARGIN, y: y - 80, width: colW, height: 84, color: LIGHT });
  page.drawText('JOB DETAILS', { x: MARGIN + 8, y: y - 12, font: boldFont, size: 7, color: MUTED });
  const jobNum = String(po.job_number ?? '');
  const jobName = String(po.job_name ?? '');
  const jobLabel = jobNum ? `#${jobNum} — ${jobName}` : jobName;
  const jobLines = wrapText(jobLabel, boldFont, 9, colW - 16);
  let jy = y - 24;
  for (const jl of jobLines.slice(0, 3)) {
    page.drawText(jl, { x: MARGIN + 8, y: jy, font: boldFont, size: 9, color: BLACK });
    jy -= 12;
  }
  if (po.job_address) {
    const addrLines = wrapText(String(po.job_address), regularFont, 8, colW - 16);
    for (const al of addrLines.slice(0, 2)) {
      page.drawText(al, { x: MARGIN + 8, y: jy, font: regularFont, size: 8, color: MUTED });
      jy -= 11;
    }
  }
  if (po.customer_name) {
    page.drawText(`Client: ${String(po.customer_name)}`, { x: MARGIN + 8, y: jy, font: regularFont, size: 8, color: MUTED });
  }

  // Contractor/assignment box
  page.drawRectangle({ x: col2x, y: y - 80, width: colW, height: 84, color: LIGHT });
  const vendorLabel = isInternal ? 'ASSIGNED TO (INTERNAL)' : 'CONTRACTOR / SUPPLIER';
  page.drawText(vendorLabel, { x: col2x + 8, y: y - 12, font: boldFont, size: 7, color: MUTED });
  let vy = y - 24;
  const vendorName = isInternal
    ? (String(po.assigned_to_name ?? 'Internal Team'))
    : (String(po.contractor_name ?? po.assigned_to_name ?? '—'));
  const vendorLines = wrapText(vendorName, boldFont, 9, colW - 16);
  for (const vl of vendorLines.slice(0, 2)) {
    page.drawText(vl, { x: col2x + 8, y: vy, font: boldFont, size: 9, color: BLACK });
    vy -= 12;
  }
  if (!isInternal) {
    if (po.contractor_email) { page.drawText(String(po.contractor_email), { x: col2x + 8, y: vy, font: regularFont, size: 8, color: MUTED }); vy -= 11; }
    if (po.contractor_phone) { page.drawText(String(po.contractor_phone), { x: col2x + 8, y: vy, font: regularFont, size: 8, color: MUTED }); vy -= 11; }
    if (po.contractor_abn)   { page.drawText(`ABN: ${String(po.contractor_abn)}`, { x: col2x + 8, y: vy, font: regularFont, size: 8, color: MUTED }); }
  }
  if (po.trade_type) {
    page.drawText(`Trade: ${String(po.trade_type)}`, { x: col2x + 8, y: y - 68, font: regularFont, size: 8, color: MUTED });
  }
  y -= 96;

  // Dates row
  const startLabel = `Start: ${fmtDate(String(po.start_date ?? ''))}`;
  const finishLabel = `Finish: ${fmtDate(String(po.finish_date ?? ''))}`;
  page.drawText(startLabel,  { x: MARGIN,          y, font: regularFont, size: 9, color: SLATE });
  page.drawText(finishLabel, { x: MARGIN + colW + 12, y, font: regularFont, size: 9, color: SLATE });
  y -= 20;

  // Instructions
  if (po.instructions) {
    page.drawRectangle({ x: MARGIN, y: y - 4, width: CONTENT_W, height: 14, color: rgb(1, 0.98, 0.93) });
    page.drawText('INSTRUCTIONS', { x: MARGIN + 6, y: y + 4, font: boldFont, size: 7, color: rgb(0.57, 0.25, 0.05) });
    y -= 18;
    const instrLines = wrapText(String(po.instructions), regularFont, 8, CONTENT_W - 12);
    for (const il of instrLines.slice(0, 8)) {
      if (y < 80) { page = newPage(); pageNum++; y = PAGE_H - 76; }
      page.drawText(il, { x: MARGIN + 6, y, font: regularFont, size: 8, color: rgb(0.47, 0.22, 0.02) });
      y -= 12;
    }
    y -= 8;
  }

  // ── Line items table ─────────────────────────────────────────────────────────
  const COL = {
    desc: { x: MARGIN + 4,   w: CONTENT_W - 180 },
    qty:  { x: MARGIN + CONTENT_W - 176, w: 44 },
    unit: { x: MARGIN + CONTENT_W - 128, w: 44 },
    rate: { x: MARGIN + CONTENT_W - 80,  w: 44 },
    amt:  { x: MARGIN + CONTENT_W - 32,  w: 36 },
  };

  // Table header — light grey, dark text
  if (y < 80) { page = newPage(); pageNum++; y = PAGE_H - 64; }
  page.drawRectangle({ x: MARGIN, y: y - 2, width: CONTENT_W, height: 16, color: LIGHT });
  page.drawText('Description',  { x: COL.desc.x, y: y + 2, font: boldFont, size: 7, color: SLATE });
  page.drawText('Qty',          { x: COL.qty.x,  y: y + 2, font: boldFont, size: 7, color: SLATE });
  page.drawText('Unit',         { x: COL.unit.x, y: y + 2, font: boldFont, size: 7, color: SLATE });
  page.drawText('Rate',         { x: COL.rate.x, y: y + 2, font: boldFont, size: 7, color: SLATE });
  page.drawText('Amount',       { x: COL.amt.x,  y: y + 2, font: boldFont, size: 7, color: SLATE });
  y -= 20;

  for (let i = 0; i < lines.length; i++) {
    const l = lines[i];
    const descLines = wrapText(String(l.description ?? ''), regularFont, 8, COL.desc.w - 4);
    const rowH = Math.max(14, descLines.length * 11 + 4);

    if (y - rowH < 60) {
      page = newPage(); pageNum++;
      y = PAGE_H - 64;
      page.drawRectangle({ x: MARGIN, y: y - 2, width: CONTENT_W, height: 16, color: LIGHT });
      page.drawText('Description', { x: COL.desc.x, y: y + 2, font: boldFont, size: 7, color: SLATE });
      page.drawText('Qty',         { x: COL.qty.x,  y: y + 2, font: boldFont, size: 7, color: SLATE });
      page.drawText('Unit',        { x: COL.unit.x, y: y + 2, font: boldFont, size: 7, color: SLATE });
      page.drawText('Rate',        { x: COL.rate.x, y: y + 2, font: boldFont, size: 7, color: SLATE });
      page.drawText('Amount',      { x: COL.amt.x,  y: y + 2, font: boldFont, size: 7, color: SLATE });
      y -= 20;
    }

    if (i % 2 === 1) {
      page.drawRectangle({ x: MARGIN, y: y - rowH + 12, width: CONTENT_W, height: rowH, color: LIGHT });
    }

    let dy = y;
    for (const dl of descLines) {
      page.drawText(dl, { x: COL.desc.x, y: dy, font: regularFont, size: 8, color: BLACK });
      dy -= 11;
    }

    const qty = parseFloat(String(l.qty ?? 1));
    const rate = parseFloat(String(l.rate ?? 0));
    const amount = parseFloat(String(l.amount ?? qty * rate));

    page.drawText(String(qty),         { x: COL.qty.x,  y, font: regularFont, size: 8, color: SLATE });
    page.drawText(String(l.unit ?? ''),{ x: COL.unit.x, y, font: regularFont, size: 8, color: SLATE });
    page.drawText(fmtCurrency(rate),   { x: COL.rate.x, y, font: regularFont, size: 8, color: SLATE });
    page.drawText(fmtCurrency(amount), { x: COL.amt.x,  y, font: boldFont,    size: 8, color: BLACK });

    y -= rowH;
  }

  if (lines.length === 0) {
    page.drawText('No line items', { x: MARGIN + CONTENT_W / 2 - 30, y, font: regularFont, size: 9, color: MUTED });
    y -= 20;
  }

  y -= 8;

  // ── Totals — rule-separated, no coloured fills ───────────────────────────────
  if (y < 100) { page = newPage(); pageNum++; y = PAGE_H - 64; }

  const totW = 200;
  const totX = PAGE_W - MARGIN - totW;

  page.drawLine({ start: { x: totX, y }, end: { x: PAGE_W - MARGIN, y }, thickness: 0.5, color: LIGHT });
  y -= 14;
  page.drawText('Subtotal (ex GST)', { x: totX, y, font: regularFont, size: 9, color: MUTED });
  page.drawText(fmtCurrency(po.subtotal), { x: PAGE_W - MARGIN - regularFont.widthOfTextAtSize(fmtCurrency(po.subtotal), 9), y, font: regularFont, size: 9, color: BLACK });
  y -= 14;
  page.drawText('GST (10%)', { x: totX, y, font: regularFont, size: 9, color: MUTED });
  page.drawText(fmtCurrency(po.gst), { x: PAGE_W - MARGIN - regularFont.widthOfTextAtSize(fmtCurrency(po.gst), 9), y, font: regularFont, size: 9, color: BLACK });
  y -= 6;
  // Bold rule above total — no filled rectangle
  page.drawLine({ start: { x: totX, y: y + 2 }, end: { x: PAGE_W - MARGIN, y: y + 2 }, thickness: 1, color: SLATE });
  y -= 4;
  page.drawText('TOTAL (inc GST)', { x: totX, y, font: boldFont, size: 10, color: BLACK });
  page.drawText(fmtCurrency(po.total), { x: PAGE_W - MARGIN - boldFont.widthOfTextAtSize(fmtCurrency(po.total), 10), y, font: boldFont, size: 10, color: BLACK });

  // ── Disclaimer ───────────────────────────────────────────────────────────────
  const disclaimer = pdfSettings.estimateDisclaimer || '';
  if (disclaimer) {
    y -= 24;
    if (y < 60) { page = newPage(); pageNum++; y = PAGE_H - 76; }
    page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_W - MARGIN, y }, thickness: 0.5, color: LIGHT });
    y -= 12;
    const dLines = wrapText(disclaimer, regularFont, 7, CONTENT_W);
    for (const dl of dLines.slice(0, 5)) {
      page.drawText(dl, { x: MARGIN, y, font: regularFont, size: 7, color: MUTED });
      y -= 10;
    }
  }

  // ── Page numbers ─────────────────────────────────────────────────────────────
  const totalPages = doc.getPageCount();
  for (let i = 0; i < totalPages; i++) {
    const pg = doc.getPage(i);
    const label = `Page ${i + 1} of ${totalPages}`;
    const lw = regularFont.widthOfTextAtSize(label, 7);
    pg.drawText(label, { x: PAGE_W - MARGIN - lw, y: 16, font: regularFont, size: 7, color: MUTED });
  }

  const pdfBytes = await doc.save();
  const safePoNum = safeName(poNumber) || `po-${poId}`;
  const filename = `${safePoNum}.pdf`;

  return {
    pdfBytes,
    filename,
    poNumber,
    poStatus,
    companyName,
    contractorName: String(po.contractor_name ?? po.assigned_to_name ?? ''),
    contractorEmail: String(po.contractor_email ?? ''),
  };
}
